name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Greetings
      run: echo "Hello Worl! This is C CI"
      shell: bash
    - name: Norminette
      run: python3 -m pip install norminette
      shell: bash
      
      
