name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Print event
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
      
      
